import {vodInfo, artworkFields, artworkUrl, musicUrl} from './songbookMedia.js';
/** Public songbook model. Never imports acquisition metadata. */
export const PAGE_SIZE=24;
export const FAVORITES_KEY='mir-songbook-favorites-v1';
export const DEMO_KEY='mir-songbook-v2-demo';
const initial=[...'ㄱㄲㄴㄷㄸㄹㅁㅂㅃㅅㅆㅇㅈㅉㅊㅋㅌㅍㅎ'];
export const normalize=(v='')=>String(v).normalize('NFKC').toLocaleLowerCase('ko-KR').replace(/[\p{P}\p{Z}\p{S}\s]/gu,'');
export function initials(v=''){return [...v].map(c=>{const n=c.charCodeAt(0)-0xac00;return n>=0&&n<=11171?initial[Math.floor(n/588)]:c;}).join('');}
export function matches(song,q=''){const text=[song.title,song.artist,...(song.aliases||[]),...(song.categories||[])].join(' ');return String(q||'').trim().split(/\s+/u).filter(Boolean).every(t=>/^[ㄱ-ㅎ]+$/u.test(t)?initials(text).includes(t):normalize(text).includes(normalize(t)));}
export function stars(value){return Number.isInteger(value)&&value>=1&&value<=5?value:null;}
export function videoUrl(value){return vodInfo(value)?.url || '';}
export function publicSong(s){return {...artworkFields(s),id:s.id,title:s.title,artist:s.artist,aliases:[...(s.aliases||[])],categories:[...(s.categories||[])],videoUrls:[...new Set((s.videoUrls||s.video_urls||[]).map(videoUrl).filter(Boolean))],difficulty:stars(s.difficulty),proficiency:stars(s.proficiency),requestStatus:s.requestStatus||s.request_status||'unreviewed'};}
export function mergeSongs(catalog,entries=[],ratings=[]){const map=new Map(catalog.map(s=>[s.id,publicSong(s)]));for(const s of entries)map.set(s.id,publicSong(s));for(const r of ratings){const s=map.get(r.song_id);if(s)s.proficiency=stars(r.proficiency);}return [...map.values()];}
export function selectSongs(songs,p=new URLSearchParams(),favorites=[]){const cats=p.getAll('category').filter(Boolean);const d=p.get('difficulty');const saved=new Set(favorites);const collator=new Intl.Collator('ko',{numeric:true,sensitivity:'base'});return songs.filter(s=>matches(s,p.get('q'))&&(!cats.length||cats.some(c=>s.categories.includes(c)))&&(!p.get('artist')||s.artist===p.get('artist'))&&(!d||(d==='unset'?s.difficulty===null:s.difficulty===Number(d)))&&(p.get('view')!=='favorites'||saved.has(s.id))&&(p.get('view')!=='videos'||s.videoUrls.length)).sort((a,b)=>p.get('sort')==='artist'?collator.compare(a.artist,b.artist)||collator.compare(a.title,b.title):p.get('sort')==='difficulty'?(b.difficulty||0)-(a.difficulty||0)||collator.compare(a.title,b.title):collator.compare(a.title,b.title));}
export function pageSlice(items,requested){const pages=Math.max(1,Math.ceil(items.length/PAGE_SIZE));const n=Number(requested);const page=Math.max(1,Math.min(pages,Number.isFinite(n)?Math.floor(n):1));return {page,pages,items:items.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE)};}
export function validateEntry(input){const title=String(input.title||'').trim(),artist=String(input.artist||'').trim();if(!title||title.length>200||!artist||artist.length>200)throw new Error('곡명과 가수를 1~200자로 입력해주세요.');const categories=[...new Set(input.categories||[])];if(!categories.length||categories.length>10||categories.some(c=>typeof c!=='string'||!c.trim()||c.length>100))throw new Error('카테고리를 1개 이상 선택해주세요.');const aliases=[...new Set(input.aliases||[])];if(aliases.length>20||aliases.some(s=>typeof s!=='string'||!s.trim()||s.length>100))throw new Error('별칭은 100자 이내, 최대 20개입니다.');const raw=(input.videoUrls||[]).filter(Boolean);if(raw.length>10||raw.some(v=>!videoUrl(v)))throw new Error('YouTube 또는 SOOP 영상 주소를 확인해주세요.');if(input.difficulty!==null&&input.difficulty!==undefined&&stars(input.difficulty)===null)throw new Error('난이도는 별 1~5개 또는 미정만 가능합니다.');const art=artworkFields(input);if(input.artworkUrl&&(!artworkUrl(input.artworkUrl)||!musicUrl(input.musicUrl)))throw new Error('앨범 이미지와 음원 연결 주소를 확인해주세요.');return {artwork_url:art.artworkUrl,music_url:art.musicUrl,album_title:art.album,id:input.id,title,artist,categories,aliases,video_urls:[...new Set(raw.map(videoUrl))],difficulty:stars(input.difficulty),request_status:['available','unavailable'].includes(input.requestStatus)?input.requestStatus:'unreviewed'};}
export function duplicateOf(songs,input){const link=artworkFields(input).musicUrl;const id=link?new URL(link).searchParams.get('i'):null;return songs.find(s=>s.id!==input.id&&((normalize(s.title)===normalize(input.title)&&normalize(s.artist)===normalize(input.artist))||(id&&s.musicUrl&&new URL(s.musicUrl).searchParams.get('i')===id)));}
export function csv(songs){const cell=v=>'"'+(/^[\s]*[=+@-]|^[\t\r]/u.test(String(v??''))?"'":'')+String(v??'').replaceAll('"','""')+'"';return '\uFEFF'+[['곡명','가수','카테고리','난이도','미르 숙련도','영상'],...songs.map(s=>[s.title,s.artist,s.categories.join(' / '),s.difficulty??'',s.proficiency??'',s.videoUrls.join(' | ')])].map(r=>r.map(cell).join(',')).join('\r\n');}
export function download(text,type,name){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
export function restrictedFetch(base,fetcher){const origin=new URL(base).origin;return (input,init={})=>{let u;try{u=new URL(typeof input==='string'?input:input.url);}catch{return Promise.reject(new Error('Invalid request'));}const method=String(init.method||input?.method||'GET').toUpperCase();const read=['GET','HEAD'].includes(method);const path=u.pathname;const auth=path==='/auth/v1/user'&&read||path==='/auth/v1/token'&&method==='POST'&&['password','refresh_token'].includes(u.searchParams.get('grant_type'))||path==='/auth/v1/logout'&&method==='POST';const table=path.match(/^\/rest\/v1\/(songbook_preview_entries|songbook_preview_ratings|songbook_preview_editors|admins)$/)?.[1];const allowedTable=table&&(read||table!=='admins'&&['POST','PATCH'].includes(method)||table==='songbook_preview_editors'&&method==='DELETE');if(u.origin!==origin||u.username||u.password||!(auth||allowedTable))return Promise.resolve(new Response(JSON.stringify({message:'노래책 검토 범위 외 요청은 차단되었습니다.'}),{status:403,headers:{'Content-Type':'application/json'}}));return fetcher(input,init);};}
