import TimelinePanel, {TimelineHistory} from '../components/songbook/TimelinePanel';
import Editor from '../components/songbook/SongEditor';
import {SongCover, VodLinks, VideoMark} from '../components/songbook/SongMedia';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {BookOpen,ChevronLeft,ChevronRight,Copy,Download,Heart,Music2,Plus,Search,SquarePlay,Star,X} from 'lucide-react';
import {IS_REVIEW_PREVIEW,IS_SONGBOOK_PREVIEW} from '../lib/preview';
import {csv,download,FAVORITES_KEY,matches,normalize,pageSlice,selectSongs,videoUrl} from '../lib/songbookV2';
import {useSongbookStore} from '../lib/songbookStore';
import '../songbook.css';
import '../songbook-v2.css';
import '../songbook-v3.css';
import '../songbook-v4.css';
export function Stars({value,label='난이도'}){return value?<span className="sb2-stars" role="img" aria-label={`${label} ${value}점`}>{[1,2,3,4,5].map(i=><Star size={15} key={i} fill={i<=value?'currentColor':'none'} className={i<=value?'':'is-empty'}/>)}</span>:<span className="sb2-unrated">{label==='미르 숙련도'?'평가 전':'미정'}</span>;}
export function StarPicker({value,onChange,disabled=false,label='미르 숙련도'}){return <fieldset className="sb2-picker"><legend>{label}</legend><div>{[1,2,3,4,5].map(i=><button key={i} type="button" disabled={disabled} aria-label={`${label} ${i}점으로 설정`} aria-pressed={value===i} onClick={()=>onChange(i)}><Star size={22} fill={i<=value?'currentColor':'none'}/></button>)}</div></fieldset>;}
function Modal({title,close,children,className=''}){const ref=useRef(null);useEffect(()=>{const prior=document.activeElement,el=ref.current,overflow=document.body.style.overflow;document.body.style.overflow='hidden';el.showModal();return()=>{el.close();document.body.style.overflow=overflow;if(prior?.isConnected)prior.focus();};},[]);function key(e){if(e.key!=='Tab')return;const nodes=[...ref.current.querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),textarea:not(:disabled),select:not(:disabled),summary')].filter(n=>n.getClientRects().length);const current=document.activeElement;if(!nodes.length)return;const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&(current===first||!nodes.includes(current))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(current===last||!nodes.includes(current))){e.preventDefault();first.focus();}}return <dialog ref={ref} className={`sb-dialog sb2-modal ${className}`} aria-labelledby="sb2-dialog-title" onKeyDown={key} onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===ref.current)close();}}><div className="sb-dialog-content"><header className="sb-dialog-top"><h2 id="sb2-dialog-title">{title}</h2><button type="button" className="sb-icon" onClick={close} aria-label="창 닫기"><X size={23}/></button></header>{children}</div></dialog>;}
export default function SongbookV2Page(){const [params,setParams]=useSearchParams();const demo=IS_SONGBOOK_PREVIEW&&params.get('demo')==='1';const store=useSongbookStore(demo);const [query,setQuery]=useState(params.get('q')||''),[favorites,setFavorites]=useState(()=>{try{const a=JSON.parse(localStorage.getItem(FAVORITES_KEY)||'[]');return Array.isArray(a)?a.filter(x=>typeof x==='string'):[];}catch{return [];}}),[message,setMessage]=useState(''),[editing,setEditing]=useState(null),[manualCopy,setManualCopy]=useState('');const q=params.get('q')||'';useEffect(()=>setQuery(q),[q]);const categories=[...new Set(store.songs.flatMap(s=>s.categories))].sort();const artists=[...new Set(store.songs.map(s=>s.artist).filter(Boolean))].sort(new Intl.Collator('ko').compare);const selectedCategories=params.getAll('category');const results=useMemo(()=>selectSongs(store.songs,params,favorites),[store.songs,params,favorites]);const page=pageSlice(results,params.get('page'));const selected=store.songs.find(s=>s.id===params.get('song'));
 function update(values,reset=true){const next=new URLSearchParams(window.location.search);['source','status'].forEach(k=>next.delete(k));for(const [k,v] of Object.entries(values)){next.delete(k);if(Array.isArray(v))v.forEach(x=>next.append(k,x));else if(v)next.set(k,v);}if(reset)next.delete('page');setParams(next);}
 function favorite(id){const next=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];setFavorites(next);try{localStorage.setItem(FAVORITES_KEY,JSON.stringify(next));}catch{setMessage('브라우저 저장이 차단되어 이번 화면에서만 유지됩니다.');}}
 async function copy(s){const text=s.artist?`${s.artist} - ${s.title}`:s.title;try{await navigator.clipboard.writeText(text);setMessage('곡 정보를 복사했습니다.');}catch{setManualCopy(text);setMessage('아래 내용을 선택하여 직접 복사해주세요.');}}
 async function rate(id,value){try{await store.saveRating(id,value);setMessage(demo?'체험 숙련도를 이 브라우저에 저장했습니다.':'미르님의 숙련도를 저장했습니다.');}catch(e){setMessage(e.message);}}
 const validFavorites=favorites.filter(id=>store.songs.some(s=>s.id===id));
 return <div className="songbook-page sb2-page"><section className="section-wrap sb-hero"><div className="sb-hero-copy"><span className="sb-overline"><BookOpen size={15}/> MIR'S SONGBOOK {IS_SONGBOOK_PREVIEW && <b>4차 검토안</b>}</span><h1>미르의 노래책<span>오늘은 어떤 노래를 들을까요?</span></h1><p>노래를 찾고, 영상을 보고,<br/>미르의 목소리로 다시 만나요.</p>{IS_SONGBOOK_PREVIEW && <div className="sb-hero-links"><Link to="/songbook/review">4차 변경점 보기 ↗</Link></div>}</div><div className="sb-record" aria-hidden="true"><div className="sb-record-ring"><div><Music2 size={38}/><b>MIR</b><span>SONGBOOK · VOL. 04</span></div></div></div></section>
 <section className="section-wrap sb2-toolbar"><div className="sb2-summary"><strong>{store.songs.length}<small>곡</small></strong><span>노래책에서 만나는 미르의 음악</span></div><div className="sb-actions">{store.canEdit&&<button type="button" className="sb-button sb-primary" onClick={()=>setEditing({})}><Plus size={17}/>노래 추가</button>}</div></section>
 {demo&&<div className="section-wrap sb2-demo" role="status"><strong>편집 체험 모드</strong><span>추가·별점 변경은 이 브라우저에만 저장되며 실제 노래책에는 반영되지 않습니다.</span><button type="button" className="sb-reset" onClick={()=>{update({demo:'',song:''});setEditing(null);}}>체험 종료</button></div>}
 {store.autoError&&<p className="section-wrap sb-auto-warning" role="status">{store.autoError}</p>}
 {store.error&&<div className="section-wrap sb2-error" role="alert">{store.error}<button type="button" className="sb-button" onClick={store.refresh}>다시 불러오기</button></div>}
 <section className="section-wrap sb-library"><div className="sb-tabs" aria-label="목록 보기">{[['','전체 노래',store.songs.length],['videos','영상 있는 곡',store.songs.filter(s=>s.videoUrls.length).length],['favorites','즐겨찾기',validFavorites.length]].map(([v,label,n])=><button key={v} type="button" aria-pressed={(params.get('view')||'')===v} onClick={()=>update({view:v,song:''})}>{label}<small>{n}</small></button>)}</div><form className="sb-search" id="songbook-search" onSubmit={e=>{e.preventDefault();update({q:query.trim(),song:''});}}><Search size={21}/><input aria-label="곡명, 가수, 초성 검색" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="곡명, 가수, 초성으로 검색해보세요"/><button className="sb-search-button">검색</button></form>
 <fieldset className="sb2-chips"><legend>카테고리 <small>다중 선택 · 선택한 분류 중 하나라도 포함</small></legend><button type="button" className={!selectedCategories.length?'is-selected':''} aria-pressed={!selectedCategories.length} onClick={()=>update({category:[]})}>전체</button>{categories.map(c=><label key={c} className={selectedCategories.includes(c)?'is-selected':''}><input type="checkbox" checked={selectedCategories.includes(c)} onChange={event=>{const current=new URLSearchParams(window.location.search).getAll('category');update({category:event.target.checked?[...new Set([...current,c])]:current.filter(x=>x!==c)});}}/>{c}</label>)}</fieldset>
 <fieldset className="sb2-chips sb2-difficulty"><legend>난이도 <small>참고 난이도 · 편곡과 키에 따라 달라질 수 있습니다.</small></legend>{[['','전체'],...[1,2,3,4,5].map(n=>[String(n),'★'.repeat(n)]),['unset','미정']].map(([v,label])=><label key={v} className={(params.get('difficulty')||'')===v?'is-selected':''}><input type="radio" name="difficulty" value={v} aria-label={v==='unset'?'난이도 미정':v?`난이도 별 ${v}개`:'난이도 전체'} checked={(params.get('difficulty')||'')===v} onChange={()=>update({difficulty:v})}/>{label}</label>)}</fieldset>
 <div className="sb-result-bar"><p role="status">총 <strong>{results.length}곡</strong>{q&&<small> · ‘{q}’ 검색</small>}</p><div><select aria-label="가수" value={params.get('artist')||''} onChange={e=>update({artist:e.target.value})}><option value="">모든 가수</option>{artists.map(a=><option key={a}>{a}</option>)}</select><select aria-label="정렬" value={params.get('sort')||''} onChange={e=>update({sort:e.target.value})}><option value="">제목순</option><option value="artist">가수순</option><option value="difficulty">난이도순</option></select><button type="button" className="sb-export" onClick={()=>download(csv(results),'text/csv;charset=utf-8','mir-songbook.csv')}><Download size={16}/><span>CSV</span></button><button type="button" className="sb-reset" onClick={()=>{setQuery('');update({q:'',category:[],difficulty:'',artist:'',sort:'',view:''});}}>초기화</button></div></div>
 <p className="sb3-legend"><span><VideoMark platform="youtube"/> YouTube VOD</span><span><VideoMark platform="soop"/> SOOP VOD</span><small>같은 플랫폼의 영상은 번호로 구분합니다.</small></p><div className="sb2-song-list" data-testid="song-list"><div className="sb2-list-head"><span>곡명 · 가수</span><span>난이도</span><span>미르 숙련도</span><span>보관</span></div>{page.items.map(s=><article className="sb2-song" key={s.id} data-song-id={s.id}><div className="sb2-song-main sb3-song-main"><SongCover song={s}/><div className="sb3-track-copy"><div className="sb2-title-line"><button type="button" className="sb2-title" aria-label={`${s.title} 상세 보기`} onClick={()=>update({song:s.id},false)}>{s.title}</button><VodLinks urls={s.videoUrls} title={s.title}/></div><p>{s.artist||'가수 미확인'}</p><div className="sb-tags">{s.categories.map(c=><span key={c}>{c}</span>)}</div></div></div><div className="sb2-rating"><small>난이도</small><Stars value={s.difficulty}/></div><div className="sb2-rating"><small>미르 숙련도</small>{store.canRate?<StarPicker value={s.proficiency} disabled={store.saving} onChange={v=>rate(s.id,v)}/>:<Stars value={s.proficiency} label="미르 숙련도"/>}</div><button type="button" className="sb-icon sb2-heart" aria-label={`${s.title} 즐겨찾기`} aria-pressed={favorites.includes(s.id)} onClick={()=>favorite(s.id)}><Heart size={18} fill={favorites.includes(s.id)?'currentColor':'none'}/></button></article>)}</div>{!page.items.length&&<div className="sb2-empty"><Music2 size={30}/><h3>조건에 맞는 노래가 없습니다.</h3><p>검색어·카테고리·난이도를 바꿔보세요.</p></div>}
 <nav className="sb-pagination" aria-label="노래 목록 페이지"><button type="button" aria-label="이전 페이지" disabled={page.page===1} onClick={()=>update({page:String(page.page-1)},false)}><ChevronLeft size={19}/></button><span>{page.page} / {page.pages}</span><button type="button" aria-label="다음 페이지" disabled={page.page===page.pages} onClick={()=>update({page:String(page.page+1)},false)}><ChevronRight size={19}/></button></nav><p className="sb-note">난이도가 미정인 곡은 임의의 별점을 넣지 않았습니다. 숙련도는 미르님의 평가를 관리자 계정으로 등록합니다.</p></section>
 {message&&<div className="section-wrap sb2-message" role="status">{message}<button type="button" className="sb-icon" aria-label="알림 닫기" onClick={()=>{setMessage('');setManualCopy('');}}><X size={16}/></button>{manualCopy&&<textarea readOnly aria-label="직접 복사할 곡 정보" value={manualCopy} onFocus={e=>e.target.select()}/>}</div>}
 {selected&&!editing&&<Modal title={selected.title} close={()=>update({song:''},false)}><div className="sb3-detail-intro"><SongCover song={selected}/><div><p>{selected.artist||'가수 미확인'}</p>{selected.album&&<small>{selected.album}</small>}</div></div><div className="sb-tags">{selected.categories.map(c=><span key={c}>{c}</span>)}</div><div className="sb2-detail-ratings"><div><h3>참고 난이도</h3><Stars value={selected.difficulty}/></div><div><h3>미르 숙련도</h3>{store.canRate?<StarPicker value={selected.proficiency} disabled={store.saving} onChange={v=>rate(selected.id,v)}/>:<Stars label="미르 숙련도" value={selected.proficiency}/>}</div></div>{message&&<p role="status" className="sb-note">{message}</p>}<div className="sb-actions"><button className="sb-button" type="button" onClick={()=>copy(selected)}><Copy size={16}/>곡 정보 복사</button>{store.canEdit&&<button type="button" className="sb-button" onClick={()=>setEditing(selected)}>곡 정보 편집</button>}{store.canRate&&<button className="sb-reset" type="button" disabled={store.saving} onClick={()=>rate(selected.id,null)}>숙련도 평가 초기화</button>}</div>{manualCopy&&<textarea className="sb2-manual" aria-label="직접 복사할 곡 정보" readOnly value={manualCopy} onFocus={e=>e.target.select()}/>}<h3>연결 영상</h3><VodLinks urls={selected.videoUrls} title={selected.title} detailed/>{!selected.videoUrls.length&&<p className="sb-note">연결된 영상이 없습니다.</p>}<TimelineHistory song={selected} client={store.client}/>{selected.aliases.length>0&&<p className="sb-note">다른 표기: {selected.aliases.join(' · ')}</p>}<p className="sb-note">신청 가능 상태: {selected.requestStatus==='available'?'가능':selected.requestStatus==='unavailable'?'불가':'확인 전'}. 실제 신청 접수 기능은 제공하지 않습니다.</p></Modal>}
 {editing&&<Editor platformSearch={!IS_REVIEW_PREVIEW} allowUnknownArtist={!IS_REVIEW_PREVIEW} Modal={Modal} StarPicker={StarPicker} key={editing.id||'new'} song={editing.id?editing:null} store={store} categories={categories} close={()=>setEditing(null)} saved={id=>{setEditing(null);update({song:id},false);setMessage(demo?'체험 변경사항을 이 브라우저에 저장했습니다.':'노래책에 저장했습니다.');}}/>}
 <TimelinePanel store={store}/>
 </div>;
}
