import {useEffect,useMemo,useRef,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {BookOpen,Search,SlidersHorizontal,Copy,Link2,Heart,Pencil,ChevronLeft,ChevronRight,X,RotateCcw,Info,Music2,Download} from 'lucide-react';
import {pageSlice,csv,download} from '../lib/songbookV2.js';
import {coverFor} from '../lib/songbookMedia.js';
import {videoPresence} from '../lib/songbookVideoPresence.js';
import {useTimedNotice} from '../lib/useTimedNotice.js';
import {STATUS,SAMPLE_SONGS,keyFor,requestText,parseSnapshot,readEdits,mergeEdits,persistEdit,selectCheckSongs,shareLink} from './model.js';
import {Dialog,Guide,QuickEdit,SongDetail,StatusBadge,Rating,VideoLinks} from './Dialogs.jsx';
import SongCategories from './SongCategories.jsx';
import './round2.css';
const BASE=import.meta.env.BASE_URL;
const attentionNames={representative:'YouTube 미연결',artist:'가수 미입력',proficiency:'숙련도 평가 전',status:'신청 상태 확인 필요'};
function Cover({song}) {const image=coverFor(song);const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[image?.url]);return <span className="ck-cover">{image&&!failed?<img src={image.url} alt="" width="52" height="52" loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>:<Music2 size={24}/>}</span>;}
export default function Preview() {
 const [params,setParams]=useSearchParams();const dataset=params.get('data')==='sample'?'sample':'snapshot',admin=params.get('mode')==='admin';
 const [snapshot,setSnapshot]=useState(null),[loadError,setLoadError]=useState(''),[reload,setReload]=useState(0);
 const [edits,setEdits]=useState({}),[favorites,setFavorites]=useState([]),[storageError,setStorageError]=useState(''),[localKey,setLocalKey]=useState('');
 const [input,setInput]=useState(params.get('q')||''),[guide,setGuide]=useState(false),[editing,setEditing]=useState(null),[resetOpen,setResetOpen]=useState(false),[manualCopy,setManualCopy]=useState(null);
 const [notice,showNotice,noticeProps]=useTimedNotice();const searchRef=useRef(null);
 const source=dataset==='sample'?SAMPLE_SONGS:snapshot?.songs||[];
 useEffect(()=>{const controller=new AbortController();let active=true;setLoadError('');const timeout=setTimeout(()=>controller.abort(),20000);fetch(`${BASE}songbook-check-snapshot.json`,{signal:controller.signal,credentials:'omit',cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('목록 조회에 실패했습니다.');return parseSnapshot(await r.json());}).then(data=>{if(active)setSnapshot(data);}).catch(error=>{if(active)setLoadError('검토용 목록을 불러오지 못했습니다. 다시 불러오거나 샘플 화면을 이용해 주세요.');}).finally(()=>clearTimeout(timeout));return()=>{active=false;clearTimeout(timeout);controller.abort();};},[reload]);
 useEffect(()=>{if(!source.length)return;try{const saved=readEdits(localStorage,dataset);mergeEdits(source,saved);setEdits(saved);const raw=JSON.parse(localStorage.getItem(keyFor(dataset)+':favorites')||'[]');setFavorites(Array.isArray(raw)?raw.filter(x=>typeof x==='string'):[]);setStorageError('');}catch{setEdits({});setFavorites([]);setStorageError('브라우저의 검토 저장 내용을 읽지 못했습니다. 검토 변경 초기화 후 다시 시도해 주세요.');}setLocalKey(dataset);},[dataset,source]);
 useEffect(()=>setInput(params.get('q')||''),[params.get('q')]);
 const songs=useMemo(()=>mergeEdits(source,edits),[source,edits]);
 const results=useMemo(()=>selectCheckSongs(songs,params,favorites,admin),[songs,params,favorites,admin]);
 const page=pageSlice(results,params.get('page')),selected=songs.find(s=>s.id===params.get('song'));
 const ready=source.length>0&&localKey===dataset;
 const categories=[...new Set(songs.flatMap(s=>s.categories))].sort(new Intl.Collator('ko').compare),cats=params.getAll('category');
 const artists=[...new Set(songs.map(s=>s.artist).filter(Boolean))].sort(new Intl.Collator('ko').compare);
 const counts=Object.fromEntries(Object.keys(STATUS).map(status=>[status,songs.filter(s=>s.requestStatus===status).length]));
 function update(values,resetPage=true,replace=false){const next=new URLSearchParams(window.location.search);for(const [k,v] of Object.entries(values)){next.delete(k);if(Array.isArray(v))v.forEach(item=>next.append(k,item));else if(v)next.set(k,v);}if(resetPage)next.delete('page');setParams(next,{replace});}
 const clearFilters=()=>update({q:'',category:[],request:'',difficulty:'',artist:'',view:'',youtube:'',soop:'',attention:'',sort:'',song:''});
 function toggleFavorite(song){const next=favorites.includes(song.id)?favorites.filter(id=>id!==song.id):[...favorites,song.id];try{localStorage.setItem(keyFor(dataset)+':favorites',JSON.stringify(next));setFavorites(next);}catch{showNotice('즐겨찾기를 브라우저에 저장하지 못했습니다.',{autoDismiss:false});}}
 async function copyText(text,message){try{await navigator.clipboard.writeText(text);showNotice(message);}catch{setManualCopy({text,message});}}
 function copySong(song){if(song.requestStatus==='unavailable')return;void copyText(requestText(song),song.requestStatus==='unreviewed'?'신청 문구를 복사했습니다. 신청 가능 여부는 먼저 확인해 주세요.':'신청 문구를 복사했습니다. 방송 채팅에 붙여넣어 주세요.');}
 function shareSong(song){void copyText(shareLink(location.origin,BASE,song.id,dataset),'검토용 곡 링크를 복사했습니다. 필터·관리자 모드·이 브라우저의 수정 내용은 공유되지 않습니다.');}
 function openEditor(song){setEditing(song);}
 function save(song,next){if(!admin||storageError)throw Error(storageError||'관리자 체험 화면에서만 변경할 수 있습니다.');const original=source.find(s=>s.id===song.id);const updated=persistEdit(localStorage,dataset,edits,original,song);setEdits(updated);
  showNotice(`「${song.title}」의 검토 변경을 이 브라우저에 저장했습니다.`);
  if(next){const index=results.findIndex(s=>s.id===song.id),nextSong=results.slice(index+1).find(s=>s.id!==song.id);setEditing(nextSong||null);}else setEditing(null);
 }
 function reset(){try{localStorage.removeItem(keyFor(dataset));localStorage.removeItem(keyFor(dataset)+':favorites');setEdits({});setFavorites([]);setStorageError('');setResetOpen(false);showNotice('이 목록의 검토 변경과 즐겨찾기를 초기화했습니다. 운영 데이터는 그대로입니다.');}catch{setStorageError('브라우저 저장소가 차단되어 초기화하지 못했습니다.');setResetOpen(false);}}
 const chips=[];
 if(params.get('q'))chips.push(['q',`검색: ${params.get('q')}`]);
 cats.forEach(c=>chips.push(['category',c,c]));
 if(Object.hasOwn(STATUS,params.get('request')))chips.push(['request',STATUS[params.get('request')]]);
 if(params.get('difficulty'))chips.push(['difficulty',params.get('difficulty')==='unset'?'난이도 미정':`난이도 ${params.get('difficulty')}점`]);
 if(params.get('artist'))chips.push(['artist',params.get('artist')]);
 if(params.get('view')==='favorites')chips.push(['view','즐겨찾기']);
 if(params.get('view')==='videos')chips.push(['view','영상 있는 곡']);
 if(admin){for(const [key,name] of [['youtube','YouTube'],['soop','SOOP']])if(['present','missing'].includes(params.get(key)))chips.push([key,`${name} ${params.get(key)==='missing'?'없음':'있음'}`]);if(attentionNames[params.get('attention')])chips.push(['attention',attentionNames[params.get('attention')]]);}
 return <div className="ck-app">
  <a className="ck-skip" href="#check-library">곡 목록으로 이동</a>
  <header className="ck-site-header"><a className="ck-brand" href={`${BASE}songbook/`}><img src={`${BASE}icon_img.png`} width="34" height="34" alt=""/>미르 <b>×</b> 청운밴드</a><nav aria-label="검토 페이지 메뉴"><span className="ck-current">노래책</span><a href="https://mir.yeop.net/" target="_blank" rel="noopener noreferrer">운영 사이트</a></nav></header>
  <main className="ck-wrap">
   <div className="ck-preview-bar"><span><b>3차 검토</b> 운영과 분리된 페이지 · 수정은 이 브라우저에만 저장</span><button type="button" className="ck-text-button" onClick={()=>setGuide(true)}><Info size={15}/>검토 안내</button></div>
   <section className="ck-hero"><div><span className="ck-eyebrow"><BookOpen size={14}/> MIR’S SONGBOOK</span><h1>오늘, 어떤 노래를 들을까요?</h1><p>미르의 노래를 찾고, 신청할 문구를 바로 복사해 보세요.</p></div><div className="ck-record" aria-hidden="true"><Music2 size={24}/><strong>MIR</strong></div></section>
   <section className="ck-preview-controls" aria-label="검토 방식"><div className="ck-mode"><button type="button" aria-pressed={!admin} onClick={()=>update({mode:'',song:''},false)}>시청자 화면</button><button type="button" aria-pressed={admin} onClick={()=>update({mode:'admin',song:''},false)}>관리자 체험</button></div><div className="ck-dataset"><label>검토 데이터<select aria-label="검토 데이터" value={dataset} onChange={e=>{setEditing(null);update({data:e.target.value==='sample'?'sample':'',q:'',category:[],request:'',difficulty:'',artist:'',view:'',youtube:'',soop:'',attention:'',song:''});}}><option value="snapshot">운영 목록 사본</option><option value="sample">기능 확인용 샘플 6곡</option></select></label><button type="button" className="ck-icon" title="검토 변경 초기화" aria-label="검토 변경 초기화" onClick={()=>setResetOpen(true)}><RotateCcw size={17}/></button></div></section>
   <p className="ck-snapshot-note">{dataset==='sample'?'샘플 곡·상태·별점·영상은 기능 확인용입니다. 실제 가창이나 신청 가능 여부를 의미하지 않습니다.':snapshot?`${new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',dateStyle:'short',timeStyle:'short'}).format(new Date(snapshot.capturedAt))} 기준 공개 목록 사본 · 운영의 추가·삭제는 실시간 동기화하지 않습니다.`:'공개 목록의 검토용 사본을 불러오는 중입니다.'}</p>
   {dataset==='snapshot'&&loadError&&<div className="ck-error" role="alert">{loadError}<button type="button" onClick={()=>setReload(n=>n+1)}>다시 불러오기</button></div>}
   {storageError&&<div className="ck-error" role="alert">{storageError}<button type="button" onClick={()=>setResetOpen(true)}>검토 변경 초기화</button></div>}
   <section className="ck-library" id="check-library" aria-label="노래 찾기" aria-busy={!ready}>
    <div className="ck-request-tabs" aria-label="신청 상태"><button type="button" aria-pressed={!Object.hasOwn(STATUS,params.get('request'))} onClick={()=>update({request:'',song:''})}>전체 <small>{songs.length}</small></button>{Object.entries(STATUS).map(([value,label])=><button type="button" key={value} aria-pressed={params.get('request')===value} onClick={()=>update({request:value,song:''})}>{label}<small>{counts[value]}</small></button>)}</div>
    <div className="ck-search-sticky"><form className="ck-search" role="search" onSubmit={e=>{e.preventDefault();update({q:input.trim(),song:''});}}><Search size={22}/><input ref={searchRef} type="search" value={input} maxLength={150} aria-label="곡명, 가수, 초성 검색" placeholder="곡명, 가수, 초성으로 찾아보세요" onChange={e=>setInput(e.target.value)}/><button className="ck-primary" type="submit">검색</button></form></div>
    <div className="ck-category-chips" aria-label="카테고리 다중 선택"><button type="button" aria-pressed={!cats.length} onClick={()=>update({category:[]})}>모든 장르</button>{categories.map(c=><button type="button" key={c} aria-pressed={cats.includes(c)} onClick={()=>update({category:cats.includes(c)?cats.filter(x=>x!==c):[...cats,c],song:''})}>{c}</button>)}</div>
    <details className="ck-filters"><summary><SlidersHorizontal size={16}/>상세 조건<span>난이도 · 가수 · 목록</span></summary><div><label>참고 난이도<select aria-label="참고 난이도" value={params.get('difficulty')||''} onChange={e=>update({difficulty:e.target.value,song:''})}><option value="">전체</option>{[1,2,3,4,5].map(v=><option key={v} value={v}>{'★'.repeat(v)}</option>)}<option value="unset">미정</option></select></label><label>가수<select aria-label="가수 조건" value={params.get('artist')||''} onChange={e=>update({artist:e.target.value,song:''})}><option value="">전체 가수</option>{artists.map(a=><option key={a} value={a}>{a}</option>)}</select></label><label>목록 보기<select aria-label="목록 보기" value={params.get('view')||''} onChange={e=>update({view:e.target.value,song:''})}><option value="">전체 노래</option><option value="favorites">이 브라우저의 즐겨찾기</option><option value="videos">영상 있는 곡</option></select></label></div></details>
    {admin&&<section className="ck-admin" aria-label="관리자 보완 작업"><header><h2><Pencil size={16}/>관리자 보완 작업</h2><span>체험 모드 · 실제 권한 변경 없음</span></header><div className="ck-admin-queue"><button type="button" aria-pressed={params.get('youtube')==='missing'&&!params.get('attention')} onClick={()=>update({youtube:'missing',soop:'',attention:'',song:''})}>YouTube 보완 <b>{songs.filter(s=>!videoPresence(s).youtube).length}</b></button>{[['representative','YouTube 미연결',s=>!s.representativeUrl],['status','상태 확인 필요',s=>s.requestStatus==='unreviewed'],['artist','가수 미입력',s=>!s.artist],['proficiency','숙련도 평가 전',s=>!s.proficiency]].map(([key,label,fn])=><button type="button" key={key} aria-pressed={params.get('attention')===key} onClick={()=>update({attention:key,youtube:'',soop:'',song:''})}>{label}<b>{songs.filter(fn).length}</b></button>)}</div><div className="ck-admin-platforms">{[['youtube','YouTube'],['soop','SOOP']].map(([key,label])=><label key={key}>{label} 링크<select aria-label={`${label} 링크 유무`} value={params.get(key)||''} onChange={e=>update({[key]:e.target.value,song:''})}><option value="">전체</option><option value="present">있음</option><option value="missing">없음</option></select></label>)}<p>두 영상 조건은 함께 적용됩니다. 링크 유무는 실제 재생·공식 영상 여부와 다릅니다.</p></div></section>}
    {chips.length>0&&<div className="ck-active-filters" aria-label="적용 중인 조건">{chips.map(([key,text,value])=><button type="button" key={key+(value||'')} aria-label={`${text} 조건 해제`} onClick={()=>update({[key]:key==='category'?cats.filter(c=>c!==value):'',song:''})}>{text}<X size={13}/></button>)}<button type="button" className="ck-text-button" onClick={clearFilters}>모두 초기화</button></div>}
    <div className="ck-result-bar"><p role="status">{ready?<><strong>{results.length}</strong>곡<span> · 전체 {songs.length}곡</span></>:'목록 준비 중…'}</p><div><button type="button" className="ck-text-button" aria-pressed={params.get('view')==='favorites'} onClick={()=>update({view:params.get('view')==='favorites'?'':'favorites',song:''})}><Heart size={15}/>즐겨찾기</button><select aria-label="정렬" value={params.get('sort')||''} onChange={e=>update({sort:e.target.value})}><option value="">제목순</option><option value="artist">가수순</option><option value="difficulty">난이도순</option></select>{admin&&<button type="button" className="ck-icon" aria-label="검색 결과 CSV" onClick={()=>download(csv(results),'text/csv;charset=utf-8','mir-songbook-check.csv')}><Download size={17}/></button>}</div></div>
    <p className="ck-request-note">곡별 신청 상태 안내입니다. 실제 접수 여부는 방송에서 확인해 주세요. 복사만으로 신청이 접수되지는 않습니다.</p>
    <div className="ck-list-heading" aria-hidden="true"><span>곡 · 신청 안내</span><span>미르 숙련도 / 참고 난이도</span><span>신청 도구</span></div>
    <div className="ck-songs">{ready&&page.items.map(song=><article className="ck-song" key={song.id} data-song-id={song.id}><div className="ck-track"><Cover song={song}/><div className="ck-track-copy"><div className="ck-title"><button type="button" onClick={()=>update({song:song.id},false)}>{song.title}</button><StatusBadge value={song.requestStatus}/></div><p>{song.artist||'가수 미확인'}</p></div><div className="ck-category-video-row"><SongCategories song={song}/><VideoLinks song={song} compact/></div>{song.publicNote&&<p className="ck-song-note">{song.publicNote}</p>}</div><Rating song={song}/><div className="ck-song-actions"><button type="button" className="ck-copy" aria-label={`${song.title} 신청 문구 복사`} disabled={song.requestStatus==='unavailable'} title={song.requestStatus==='unavailable'?'신청 불가로 안내된 곡입니다.':undefined} onClick={()=>copySong(song)}><Copy size={15}/>{song.requestStatus==='unavailable'?'신청 불가':'신청 문구'}</button><button type="button" className="ck-icon" aria-label={`${song.title} 곡 링크 복사`} onClick={()=>shareSong(song)}><Link2 size={17}/></button><button type="button" className="ck-icon" aria-label={`${song.title} 즐겨찾기`} aria-pressed={favorites.includes(song.id)} onClick={()=>toggleFavorite(song)}><Heart size={18} fill={favorites.includes(song.id)?'currentColor':'none'}/></button>{admin&&<button type="button" className="ck-quick" aria-label={`${song.title} 빠른 수정`} onClick={()=>openEditor(song)}><Pencil size={14}/>빠른 수정</button>}</div></article>)}</div>
    {ready&&!results.length&&<div className="ck-empty"><Search size={30}/><h2>조건에 맞는 곡이 없습니다.</h2><p>위의 적용 중인 조건을 하나씩 해제하거나, 전체 조건을 초기화해 보세요.</p><button type="button" onClick={clearFilters}>조건 초기화</button></div>}
    {ready&&<nav className="ck-pagination" aria-label="노래 목록 페이지"><button type="button" aria-label="이전 페이지" disabled={page.page===1} onClick={()=>update({page:String(page.page-1),song:''},false)}><ChevronLeft size={18}/></button><span>{page.page} / {page.pages}</span><button type="button" aria-label="다음 페이지" disabled={page.page===page.pages} onClick={()=>update({page:String(page.page+1),song:''},false)}><ChevronRight size={18}/></button></nav>}
   </section>
   <footer className="ck-page-footer"><span>미르 × 청운밴드 · 노래책 사용성 3차 검토</span><button type="button" className="ck-text-button" onClick={()=>setGuide(true)}>변경점과 검토 범위</button></footer>
  </main>
  {notice&&<div className="ck-toast" role="status" {...noticeProps}><span>{notice}</span><button type="button" className="ck-icon" aria-label="알림 닫기" onClick={()=>showNotice('')}><X size={17}/></button></div>}
  {selected&&!editing&&!guide&&!manualCopy&&<SongDetail song={selected} close={()=>update({song:''},false)} copy={copySong} share={shareSong} admin={admin} edit={()=>openEditor(selected)} notice={notice} noticeProps={noticeProps}/>}
  {editing&&admin&&<QuickEdit key={editing.id} song={editing} close={()=>setEditing(null)} save={save} notice={notice} hasNext={results.findIndex(s=>s.id===editing.id)<results.length-1}/>}
  {guide&&<Guide close={()=>setGuide(false)}/>}
  {resetOpen&&<Dialog title="검토 변경 초기화" close={()=>setResetOpen(false)}><div className="ck-dialog-body"><p>선택한 {dataset==='sample'?'샘플':'운영 사본'} 목록에서 이 브라우저에 저장한 수정 내용과 즐겨찾기만 초기화합니다. 실제 운영 데이터와 다른 목록의 검토 내용은 변경하지 않습니다.</p><button type="button" className="ck-primary" onClick={reset}>검토 변경 초기화하기</button></div></Dialog>}
  {manualCopy&&<Dialog title="직접 복사" close={()=>setManualCopy(null)}><div className="ck-dialog-body"><p>자동 복사를 사용할 수 없습니다. 아래 내용을 선택해 복사해 주세요.</p><textarea readOnly aria-label="직접 복사할 내용" rows={4} value={manualCopy.text} onFocus={e=>e.target.select()} autoFocus/><p className="ck-muted">신청 문구는 방송 채팅에 붙여넣어야 합니다. 곡 링크에는 이 브라우저의 검토 변경이 포함되지 않습니다.</p></div></Dialog>}
 </div>;
}
